fix ./service scripts

diff --git a/service-install b/service-install
--- a/service-install
+++ b/service-install
@@ -1,9 +1,37 @@
 #!/usr/bin/env zsh
 
+echo "Copying mediaserver files to /etc/systemd/system"
 sudo cp -f ./mediaserver.service /etc/systemd/system/mediaserver.service
+if [[ "$?" != "0" ]]; then
+ echo "Could not copy ./mediaserver.service to /etc/systemd/system"
+ exit 1
+fi
 sudo cp -f ./mediaserver-update.service /etc/systemd/system/mediaserver-update.service
+if [[ "$?" != "0" ]]; then
+ echo "Could not copy ./mediaserver-update.service to /etc/systemd/system"
+ exit 1
+fi
 sudo cp -f ./mediaserver-update.timer /etc/systemd/system/mediaserver-update.timer
+if [[ "$?" != "0" ]]; then
+ echo "Could not copy ./mediaserverupdate-timer to /etc/systemd/system"
+ exit 1
+fi
 
+echo "Reloading systemd daemon"
 sudo systemctl daemon-reload
+if [[ "$?" != "0" ]]; then
+ echo "Reloading daemon failed"
+ exit 1
+fi
+
+echo "enabling services"
 sudo systemctl enable mediaserver-update.timer
+if [[ "$?" != "0" ]]; then
+ echo "Could not enable mediaserver-update.timer"
+ exit 1
+fi
 sudo systemctl enable mediaserver.service
+if [[ "$?" != "0" ]]; then
+ echo "Could not enable mediaserver.service"
+ exit 1
+fi
diff --git a/service-start b/service-start
--- a/service-start
+++ b/service-start
@@ -1,4 +1,8 @@
 #!/usr/bin/env zsh
 
 sudo systemctl start mediaserver.service &
-echo "service started, use ./service-logs to check progress"
+if [[ "$?" != "0" ]]; then
+  echo "Service start failed."
+else
+  echo "service started, use ./service-logs to check progress"
+fi
diff --git a/service-stop b/service-stop
--- a/service-stop
+++ b/service-stop
@@ -1,4 +1,8 @@
 #!/usr/bin/env zsh
 
 sudo systemctl stop mediaserver.service &
-echo "service stopping, use ./service-logs to check progress, or docker ps/docker stats"
+if [[ "$?" != "0" ]]; then
+  echo "Service stop failed!"
+else
+  echo "service stopping, use ./service-logs to check progress, or docker ps/docker stats"
+fi
diff --git a/service-uninstall b/service-uninstall
--- a/service-uninstall
+++ b/service-uninstall
@@ -1,6 +1,22 @@
 #!/usr/bin/env zsh
 
+echo "Disabling services"
 sudo systemctl disable mediaserver-update.timer
+if [[ "$?" != "0" ]]; then
+  echo "could not disable mediaserver-update.timer"
+  exit 1
+fi
 sudo systemctl disable mediaserver.service
+if [[ "$?" != "0" ]]; then
+  echo "could not disable mediaserver.service"
+  exit 1
+fi
 
+echo "Removing service files"
 sudo rm -f /etc/systemd/system/mediaserver*
+if [[ "$?" != "0" ]]; then
+  echo "Deleting the mediaserver files failed, they may already be missing"
+  echo "ls /etc/systemd/system/mediaserver*"
+fi
+
+sudo systemctl daemon-reload
